# Generated by Django 5.2.8 on 2025-11-17 15:02

import django.core.validators
import django.db.models.deletion
import personaldetail.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=personaldetail.models.bank_logo_upload_to)),
                ('code', models.CharField(blank=True, help_text='Optional bank identifier code', max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Branch display name', max_length=200)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='personaldetail.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['province__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipalities', to='personaldetail.district')),
            ],
            options={
                'ordering': ['district__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=personaldetail.models.person_photo_upload_to)),
                ('computer_code', models.CharField(help_text='Numeric code only', max_length=30, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only digits are allowed.')])),
                ('identity_no', models.CharField(max_length=64, unique=True)),
                ('is_working', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='personaldetail.person')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z-]+$', 'Only letters, digits and hyphen allowed')])),
                ('is_primary', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='personaldetail.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='personaldetail.bankbranch')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='personaldetail.person')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='personaldetail.person')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('symbol_image', models.ImageField(blank=True, null=True, upload_to=personaldetail.models.symbol_image_upload_to)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='personaldetail.post'),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='personaldetail.province'),
        ),
        migrations.CreateModel(
            name='SpecificWork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='specific_works',
            field=models.ManyToManyField(blank=True, related_name='persons', to='personaldetail.specificwork'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at_nepali', models.CharField(blank=True, editable=False, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ward_no', models.PositiveSmallIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='personaldetail.municipality')),
            ],
            options={
                'ordering': ['municipality__name', 'ward_no'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='branch_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_branch', to='personaldetail.ward'),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_branches', to='personaldetail.ward'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['name'], name='personaldet_name_8e91df_idx'),
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['district', 'name'], name='personaldet_distric_3299b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together={('district', 'name')},
        ),
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['person', 'is_primary'], name='personaldet_person__0639cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailaddress',
            unique_together={('person', 'email')},
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['person', 'bank'], name='personaldet_person__ebcd5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('bank', 'account_number')},
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['person', 'is_primary'], name='personaldet_person__18e35e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('person', 'number')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='personaldet_slug_2b620e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['name'], name='personaldet_name_48c86b_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['name'], name='personaldet_name_e4cff0_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['province', 'name'], name='personaldet_provinc_53a2bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('province', 'name')},
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['municipality', 'ward_no'], name='personaldet_municip_84a725_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('municipality', 'ward_no')},
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='personaldet_name_727fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['computer_code'], name='personaldet_compute_ce9de4_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['identity_no'], name='personaldet_identit_b52da1_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_at'], name='personaldet_created_ea8154_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('computer_code',), name='unique_computer_code'),
        ),
        migrations.AddIndex(
            model_name='bankbranch',
            index=models.Index(fields=['bank', 'name'], name='personaldet_bank_id_4e4e19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankbranch',
            unique_together={('bank', 'name', 'ward')},
        ),
    ]
