# Generated by Django 5.2.8 on 2025-11-17 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldetail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AddField(
            model_name='specificwork',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['slug'], name='personaldet_slug_a4bd2a_idx'),
        ),
        migrations.AddIndex(
            model_name='bankbranch',
            index=models.Index(fields=['bank', 'slug'], name='personaldet_bank_id_58f358_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['province', 'slug'], name='personaldet_provinc_67078a_idx'),
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['district', 'slug'], name='personaldet_distric_a3600c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['slug'], name='personaldet_slug_c2f162_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['slug'], name='personaldet_slug_8e2a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['municipality', 'slug'], name='personaldet_municip_ec90ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankbranch',
            constraint=models.UniqueConstraint(fields=('bank', 'slug'), name='unique_branch_slug_per_bank'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('province', 'slug'), name='unique_district_slug_per_province'),
        ),
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('district', 'slug'), name='unique_municipality_slug_per_district'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('municipality', 'slug'), name='unique_ward_slug_per_municipality'),
        ),
    ]
